import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}

      >
        <div
          className="fixed inset-0 -z-10 bg-cover bg-center scale-110 blur-2xl"
          style={{
            backgroundImage: "url('/assets/banner.png')",
          }}
        />
        {children}
      </body>
    </html>
  );
}
